### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by TheSloPro** [outlaylol/BotFarmer#14]
Hi

I think that's a problem with discord.js@13.6.0 compatibility (latest). Can you please make it compatible with latest discord.js? Here's full error:
`/home/runner/autogrinder/node_modules/discord.js/src/client/ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at ClientDataManager.newChannel (/home/runner/autogrinder/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/home/runner/autogrinder/node_modules/discord.js/src/structures/Guild.js:206:68)
    at new Guild (/home/runner/autogrinder/node_modules/discord.js/src/structures/Guild.js:72:12)
    at ClientDataManager.newGuild (/home/runner/autogrinder/node_modules/discord.js/src/client/ClientDataManager.js:26:19)
    at ReadyHandler.handle (/home/runner/autogrinder/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:20:91)
    at WebSocketPacketManager.handle (/home/runner/autogrinder/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/autogrinder/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/autogrinder/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/runner/autogrinder/node_modules/ws/lib/event-target.js:120:16)`

**Comment by outlaylol** [comment]
Id have to rewrite everything, this lib has cancer, dont use it.
