### ISSUE TITLE
Discord Missing Api Permission error

### ISSUE THREAD

**Issue by CodeDaddyy** [outlaylol/BotFarmer#5]
UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at RequestHandler.execute (D:\BotFarmer\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (D:\BotFarmer\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async MessageManager.delete (D:\BotFarmer\node_modules\discord.js\src\managers\MessageManager.js:126:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by outlaylol** [comment]
Which command
